### ISSUE TITLE
Collection group query onSnapshot stops being called

### ISSUE THREAD

**Issue by jmacedoit** [googleapis/nodejs-firestore#1057] opened 2020-04-30 14:31 UTC
#### Environment details

  - OS: Alpine
  - Node.js version: 12.16
  - npm version: 
  - `@google-cloud/firestore` version: 3.7.5

#### Steps to reproduce

We have a gateway that listens to a collection group and processes new snapshots (frequency: 5 - 100 snapshots / minute):
```
  var eventQuery = database.collectionGroup('events')
    .where('state', '==', messageState.pending)
    .orderBy('createdAt');

  eventQuery.onSnapshot(processEventSnapshot);
```

Lately this stops working after some time and we stop getting new snapshots. (about a pair of hours).
We don't know what causes this. Obviously there are new events that should trigger onSnapshot since restarting the process solves the problem.

Here are the logs of our gateway at 5 am:
```
Firestore (3.7.5) 2020-04-30T04:59:12.020Z ZOE6F [Firestore.requestStream]: Received response: {"documentChange": ..., "name":"projects/X/databases/(default)/documents/tenants/X/channels/315559751805571/streams/3427895583892103/events/JfQzblpW8JqsKetlT5w3","createTime":{"seconds":"1588222752","nanos":1119000},"updateTime":{"seconds":"1588222752","nanos":1119000}}},"responseType":"documentChange"}
Firestore (3.7.5) 2020-04-30T04:59:12.021Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,223,152,212,231,174,143,233,2]},"readTime":{"seconds":"1588222752","nanos":1119000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T04:59:12.021Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T04:59:12.021Z ZOE6F [Watch.pushSnapshot]: Sending snapshot with 1 changes and 3182 documents
Firestore (3.7.5) 2020-04-30T05:00:13.077Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,141,195,227,132,175,143,233,2]},"readTime":{"seconds":"1588222813","nanos":69709000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:00:13.077Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:01:11.017Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,162,246,179,160,175,143,233,2]},"readTime":{"seconds":"1588222871","nanos":10082000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:01:11.017Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:02:41.039Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,203,179,170,203,175,143,233,2]},"readTime":{"seconds":"1588222961","nanos":31627000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:02:41.039Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:04:11.062Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,226,247,160,246,175,143,233,2]},"readTime":{"seconds":"1588223051","nanos":54050000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:04:11.062Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:05:41.083Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,187,183,151,161,176,143,233,2]},"readTime":{"seconds":"1588223141","nanos":75899000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:05:41.083Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:07:11.105Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,233,249,141,204,176,143,233,2]},"readTime":{"seconds":"1588223231","nanos":98089000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:07:11.105Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:08:41.127Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,139,185,132,247,176,143,233,2]},"readTime":{"seconds":"1588223321","nanos":119883000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:08:41.127Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:10:11.149Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,225,251,250,161,177,143,233,2]},"readTime":{"seconds":"1588223411","nanos":142113000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:10:11.149Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:11:41.170Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,230,185,241,204,177,143,233,2]},"readTime":{"seconds":"1588223501","nanos":163750000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:11:41.170Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:13:11.193Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,128,254,231,247,177,143,233,2]},"readTime":{"seconds":"1588223591","nanos":186176000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:13:11.193Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:14:41.216Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,139,198,222,162,178,143,233,2]},"readTime":{"seconds":"1588223681","nanos":209099000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:14:41.216Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:16:11.239Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,172,137,213,205,178,143,233,2]},"readTime":{"seconds":"1588223771","nanos":231404000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:16:11.239Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:17:41.261Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,205,200,203,248,178,143,233,2]},"readTime":{"seconds":"1588223861","nanos":253197000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:17:41.261Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:19:11.282Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,215,136,194,163,179,143,233,2]},"readTime":{"seconds":"1588223951","nanos":275095000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:19:11.283Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:20:41.304Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,144,203,184,206,179,143,233,2]},"readTime":{"seconds":"1588224041","nanos":297296000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:20:41.304Z ZOE6F [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T05:22:11.326Z ZOE6F [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,168,138,175,249,179,143,233,2]},"readTime":{"seconds":"1588224131","nanos":319080000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T05:22:11.326Z ZOE6F [Watch.onData]: Processing target change
```

This goes on until 6:07am, when our gateway restarted (it restarts every 3 hours to have some tolerance to these types of failures) and normal activity is resumed...

```
Firestore (3.7.5) 2020-04-30T06:08:12.896Z ##### [Firestore]: Initialized Firestore
Firestore (3.7.5) 2020-04-30T06:08:12.905Z bHJ8x [ClientPool.acquire]: Creating a new client
Firestore (3.7.5) 2020-04-30T06:08:13.006Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (3.7.5) 2020-04-30T06:08:13.006Z bHJ8x [Firestore.requestStream]: Sending request: {"database":"projects/X/databases/(default)","addTarget":{"query":{"parent":"projects/X/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"events","allDescendants":true}],"where":{"fieldFilter":{"field":{"fieldPath":"state"},"op":"EQUAL","value":{"stringValue":"PENDING"}}},"orderBy":[{"field":{"fieldPath":"createdAt"},"direction":"ASCENDING"}]}},"targetId":1}}
Firestore (3.7.5) 2020-04-30T06:08:13.016Z bHJ8x [Firestore._initializeStream]: Sending request: {"database":"projects/X/databases/(default)","addTarget":{"query":{"parent":"projects/X/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"events","allDescendants":true}],"where":{"fieldFilter":{"field":{"fieldPath":"state"},"op":"EQUAL","value":{"stringValue":"PENDING"}}},"orderBy":[{"field":{"fieldPath":"createdAt"},"direction":"ASCENDING"}]}},"targetId":1}}
Firestore (3.7.5) 2020-04-30T06:08:13.028Z bHJ8x [Firestore._initializeStream]: Marking stream as healthy
Firestore (3.7.5) 2020-04-30T06:08:13.029Z bHJ8x [Firestore._initializeStream]: Releasing stream
Firestore (3.7.5) 2020-04-30T06:08:13.029Z bHJ8x [Watch.initStream]: Opened new stream
Firestore (3.7.5) 2020-04-30T06:08:13.295Z bHJ8x [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[1],"targetChangeType":"ADD","cause":null,"resumeToken":{"type":"Buffer","data":[]},"readTime":null},"responseType":"targetChange"}
Firestore (3.7.5) 2020-04-30T06:08:13.295Z bHJ8x [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-04-30T06:08:13.372Z bHJ8x [Firestore.requestStream]: Received response: {"documentChange":... "name":"projects/X/databases/(default)/documents/tenants/X/channels/315559751805571/streams/2250381201726111/events/DP433Z2tOQsbUog3H7ZX","createTime":{"seconds":"1583919154","nanos":806271000},"updateTime":{"seconds":"1583919154","nanos":806271000}}},"responseType":"documentChange"}
Firestore (3.7.5) 2020-04-30T06:08:13.373Z bHJ8x [Watch.onData]: Processing change event
Firestore (3.7.5) 2020-04-30T06:08:13.373Z bHJ8x [Watch.onData]: Received document change
```

The strangest part is, we have 2 different firestore projects and each with a different instance of the same gateway code, and this only happens in one of them.

**Comment by schmidt-sebastian** [comment] 2020-05-01 23:08
@jmacedoit It sounds like your connection drops without us noticing it. Do you mind playing with the keep-alive settings mentioned here: https://github.com/grpc/grpc-node/issues/154

It sounds like we may need to turn on keep alive by default.

**Comment by jmacedoit** [comment] 2020-05-02 17:55
@schmidt-sebastian Can you elaborate a bit more? Which of these settings
```
"grpc.keepalive_time_ms"
"grpc.keepalive_timeout_ms"
"grpc.keepalive_permit_without_calls"
``` 
And with which values should I try them? (And how do it in firestore admin sdk?)

**Comment by schmidt-sebastian** [comment] 2020-05-02 18:18
@jmacedoit I would start with something like this:

```
const firestore = admin.firestore();
firestore.settings({ grpc.keepalive_time_ms: 2000, grpc.keepalive_timeout_ms: 500 });
```

This means that the GRPC is going to send a "keep-alive" request every 2 seconds and will consider the connection dead if no response is received within 500 ms.

**Comment by jmacedoit** [comment] 2020-05-02 22:30
@schmidt-sebastian Thank you. We were actually planning to implement something like this mechanism to mitigate this. Didn't know there was a setting for it already integrated with grpc.

We will try this when we get the chance to and I will get back to you with feedback.

**Comment by jmacedoit** [comment] 2020-05-07 15:09
@schmidt-sebastian 
This doesn't seem to work. We tried it with:
grpc.keepalive_time_ms: 10000, grpc.keepalive_timeout_ms: 1000

But the same happened again:
  ```
Firestore (3.7.5) 2020-05-07T13:53:30.963Z GrI0g [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[1],"targetChangeType":"CURRENT","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,182,143,241,163,243,161,233,2]},"readTime":{"seconds":"1588859607","nanos":205814000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-05-07T13:53:30.964Z GrI0g [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-05-07T13:53:30.964Z GrI0g [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,182,143,241,163,243,161,233,2]},"readTime":{"seconds":"1588859607","nanos":205814000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-05-07T13:53:30.964Z GrI0g [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-05-07T13:53:31.175Z GrI0g [Watch.pushSnapshot]: Sending snapshot with 6575 changes and 6575 documents
Firestore (3.7.5) 2020-05-07T13:53:31.334Z GrI0g [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,220,207,213,165,243,161,233,2]},"readTime":{"seconds":"1588859610","nanos":949596000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-05-07T13:53:31.334Z GrI0g [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-05-07T13:54:23.294Z GrI0g [Firestore.requestStream]: Received response:
Firestore (3.7.5) 2020-05-07T13:54:23.294Z GrI0g [Watch.onData]: Processing change event
Firestore (3.7.5) 2020-05-07T13:54:23.294Z GrI0g [Watch.onData]: Received document change
Firestore (3.7.5) 2020-05-07T13:54:23.295Z GrI0g [Firestore.requestStream]: Received response: {"targetChange":{"targetIds":[],"targetChangeType":"NO_CHANGE","cause":null,"resumeToken":{"type":"Buffer","data":[10,9,8,191,152,207,190,243,161,233,2]},"readTime":{"seconds":"1588859663","nanos":273023000}},"responseType":"targetChange"}
Firestore (3.7.5) 2020-05-07T13:54:23.295Z GrI0g [Watch.onData]: Processing target change
Firestore (3.7.5) 2020-05-07T13:54:23.295Z GrI0g [Watch.pushSnapshot]: Sending snapshot with 1 changes and 6576 documents
```

This is quite strange, if grpc is monotoring itself it *should* work right?

**Comment by schmidt-sebastian** [comment] 2020-05-08 18:04
Interesting. One thing that stands out to me is that you are using a relatively large collection. Do you happen to see an increase in CPU usage? I wonder if the SDK just cannot handle your workload. 

I will try to create a repo with a couple of thousand documents to see if there is a processing issue on our end.

**Comment by schmidt-sebastian** [comment] 2020-05-08 18:41
I do not see an increase in CPU load with a snapshot containing 10k documents.

**Comment by jmacedoit** [comment] 2020-05-14 17:19
Sorry for answering only now, but we investigated this several times and neither memory nor cpu load appeared to increase particularly when this happened

**Comment by chrisfraser** [comment] 2020-06-07 19:37
I am getting similar problems on a normal collection query in a live environment and it is killing me.

@schmidt-sebastian I have emailed you all the logs and info.
gprc setting have not helped:
```
this.firestore.settings({
  'grpc.keepalive_time_ms': 5000,
  'grpc.keepalive_timeout_ms': 2000,
  'grpc.keepalive_permit_without_calls': 1,
  'grpc.http2.max_pings_without_data': 0,
  'grpc.http2.min_time_between_pings_ms': 5000,
  'grpc.http2.min_ping_interval_without_data_ms': 2000,
});
```
Please help.

**Comment by schmidt-sebastian** [comment] 2020-06-08 22:36
@chrisfraser's logs show a single Watch target that stalls after receiving a couple thousand documents, while another Watch target remains active. We still don't know what the root cause is, but this seems to rule out CPU usage issues on the client.

**Comment by chrisfraser** [comment] 2020-06-11 21:30
Is there any update here or stable version to roll back to? We are losing customers because of this.

**Comment by schmidt-sebastian** [comment] 2020-06-11 21:41
We have reason to believe that this is backend issue related to internal Quota. The backend team is looking at this via internal bug b/156308554.

If helpful, we could probably provide a temporary mitigation that restarts idle stream after certain thresholds. We can restart streams internally without re-downloading all data.

**Comment by chrisfraser** [comment] 2020-06-11 21:52
Any mitigating factor would be greatly appreciated. Even an error that we could react to would be a solution. Currently it listeners die without any way of knowing.

**Comment by schmidt-sebastian** [comment] 2020-06-15 20:50
A workaround is now in review: https://github.com/googleapis/nodejs-firestore/pull/1220

**Comment by chrisfraser** [comment] 2020-06-17 19:27
@schmidt-sebastian The above fix is a work around. Can you give us any feedback on progress resolving the underlying issue?

**Comment by schmidt-sebastian** [comment] 2020-06-17 19:56
Please file a customer support ticket, which will get routed to the backend team that has access to a lot more information than either of us. Thank you.

**Closed** 2020-06-19 18:21 UTC
Labels: api: firestore, priority: p2, type: bug

**Comment by chrisfraser** [comment] 2020-07-07 10:33
This issue has not been fixed. #1220 Is a workaround for an underlying issue that has not been resolved.
