### ISSUE TITLE
firestore issue with storing documents

### ISSUE THREAD

**Issue by siyah97** [googleapis/nodejs-firestore#1551] opened 2021-07-01 07:19 UTC
So this problem only started recently literally out of nowhere as I didn't make any code changes. 
here is a snippet of the issue: 

Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Caused by: Error
    at WriteBatch.commit (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:414:23)
    at DocumentReference.create (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:291:14)
    at CollectionReference.add (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:1967:28)
    at /workspace/index.js:14:44
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/providers/https.js:51:16)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:100:17
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 13,
  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
} 

I really dont know how to deal with this. I tried changing Node versions as well as admin sdk versions but it still throws this error.
Here are my dependencies for my functions:

"dependencies": {
    "axios": "^0.21.1",
    "dotenv": "^10.0.0",
    "firebase-admin": "8.10.0",
    "firebase-functions": "^3.14.1"
  },

Thank you!

**Comment by crwilcox** [comment] 2021-07-01 16:19
Thank you for filing this. I am closing this as being a duplicate of to https://github.com/googleapis/nodejs-firestore/issues/1023

Also, where was this code running?

Can you share the code at:
```
at /workspace/index.js:14:44
```

**Closed by crwilcox** 2021-07-01 16:19 UTC
Labels: api: firestore

**Comment by siyah97** [comment] 2021-07-01 17:55
Thank you for your timely response.
here is the code: 

const admin = require('firebase-admin');
require('dotenv').config();
const bearerToken = process.env.TEST_BEARER_TOKEN;
admin.initializeApp();


exports.transactionWebhook = functions.https.onRequest((request, response)=>{
    functions.logger.info(request.body); // this is line 14
    admin.firestore().collection('events').add(request.body).then(res=>{
        functions.logger.info("event saved");
        response.sendStatus(200);
    }).catch(error=>{
        functions.logger.error(error);
        response.sendStatus(200);
    })
});
