### ISSUE TITLE
Issue: Order by clause cannot contain more fields after the key

### ISSUE THREAD

**Issue by ngoctienvc** [googleapis/nodejs-firestore#1472] opened 2021-04-13 04:50 UTC
**Environment details**
> OS: Firebase Function NodeJS,
>       Node.js version: 14.16.1
>       firebase-admin version: 9.5.0

**Steps to reproduce**
```
     const projectFilter = db
      .collection('Project')
      .where('__name__', 'in', projectIds)
      .orderBy('__name__')
      .orderBy('projectName')
      .select(...field);
```
Implement follow by lasted comment this issue: https://github.com/googleapis/nodejs-firestore/issues/990.
![image](https://user-images.githubusercontent.com/6822108/114499063-928d1100-9c4f-11eb-8474-08a34f5ec851.png)
_I also try FieldPath.documentId() replace to __name__. But it still have same problem._
**Expected**: able to query sort multile field include document ID in single collection.

**Actual**:

> Error: Error: 3 INVALID_ARGUMENT: order by clause cannot contain more fields after the key
>     at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by dconeybe** [comment] 2021-04-13 19:47
Hi @ngoctienvc. The reason that your are getting an error from the query is that the second order by, `.orderBy('projectName')`, has no effect on the ordering. Since the document names in a collection are guaranteed to be unique, it does not make sense to add any "order by" clauses *after* the `.orderBy('__name__')` clause. That is what the error message "order by clause cannot contain more fields after the key" is trying to convey.

In other words, think of the first "order by" as the desired ordering, and the second "order by" as a tie breaker if two documents have the same `__name__`. Since it is impossible for two documents in a collection to have the same name, the second "order by" is extraneous and will never be used.

I assume that your desired query omits the `.orderBy('__name__')` clause completely, and that you are only adding it to fix the error you would have gotten if the first "order by" field was anything other than `__name__`. Unfortunately, this is not possible because the "where" clause uses an "in" query, which requires the first "order by" clause be on the same field. This is how Firestore's indexing works to maintain fast queries. If you want to order by project ID then you will need to do that sorting locally on the result returned from Firestore.

I'm going to close this issue, but feel free to reply if your question/request has not been addressed to your satisfaction!

**Closed by dconeybe** 2021-04-13 19:47 UTC
Labels: api: firestore

**Comment by LeadDreamer** [comment] 2021-04-21 22:47
I have a case that your answer does not address, but the issue prevents it from operating.

My database structure is *very* tree-like, and makes extensive use of collection groups - i.e. I have multiple documents in the "TopLevel" collection; each document has its own collection "SecondLevel" collection; each document in a "SecondLevel" has its own "ThirdLevel" collection; etc.

I have found an efficient way to use a collection group on say a "FourthLevel" collection that *all* belong as part of the tree below a particular document is to take advantage of the *fact* that '__name__' is ACTUALLY the full path to the document including it's particular ID (don't argue about this; it's already known true https://stackoverflow.com/questions/56149601/firestore-collection-group-query-on-documentid/58104104#58104104 ). 

Namely, to use an inequality on the '__name__' fields similar to:

  const ownerPath = owner.refPath;
  let nextPath = ownerPath.slice();
  const nextLength = nextPath.length;
  let lastChar = nextPath.charCodeAt(nextLength - 1);
  nextPath = nextPath
    .slice(0, nextLength - 1)
    .concat(String.fromCharCode(lastChar + 1));

  const ownerParts = [
    {
      fieldRef: "__name__",
      opStr: ">",
      value: ownerPath
    },
    {
      fieldRef: "__name__",
      opStr: "<",
      value: nextPath
    }
  ];

The result of this operation as a set of "where" clauses on a collectionGroup query will return all the documents that are in the CollectionGroup (in this example "FourthLevel") that are children of a particular Parent document, regardless of the branching between the parent and the children.  An obvious limitation is no other inequality clause can be used in the query.

The problem comes about in trying to SORT the result (purely out of convenience, to be totally honest) - the '__name__' fields in this case are clearly NOT the same, BUT the first .sortBy() is STILL required to be '__name__' - which also then means NO OTHER SORT IS POSSIBLE (exactly same same error as reported above).

This is NOT the same case as above - the '__name__' fields are NOT identical - and it most certainly IS reasonable to want to sort the results.  This is a bug and/or a hidden limitation of your indexing.

**Comment by dconeybe** [comment] 2021-06-04 18:35
Hi @LeadDreamer, apologies for the extremely delayed response. This one fell through the cracks for me.

I've read through your comment several times and I'm having trouble understanding both the structure of the documents in your database and the query that you are having issues with. If you'd still like to discuss, please open a new issue, tag me in it, and include the URL of this issue in the description so they get linked. Optionally, if you can provide an app that populates the database then issues the problematic query, that would be helpful for me to investigate and reproduce.

Again, I'm sorry for taking so long to respond.
