### ISSUE TITLE
FieldValue functions/sentinels not working properly since v3.8

### ISSUE THREAD

**Issue by jessmorecroft** [googleapis/nodejs-firestore#1084] opened 2020-05-18 10:37 UTC
I upgraded this library today to 3.8 and broke my app. Looks like the issue is with FieldValue.timestamp() and FieldValue.increment(..) and maybe others, though I've only checked these. Basically these values aren't getting to the server it appears. It works for every version up till 3.8, the current latest, so presumably something in there has busted this.

Note I am testing against the gcloud emulator running in Docker (mtlynch/firestore-emulator-docker) ... it's a fairly significant break so perhaps I've missed something obvious here, or this is even a weird incompatibility with the emulator.

#### Environment details

  - OS: MacOSX
  - Node.js version: 12.6
  - npm version: 6.13.4
  - `@google-cloud/firestore` version: 3.8

#### Steps to reproduce

  1. Run the following code - basically just the "quickstart" in the doc modified to use FieldValue:
```
const { Firestore, FieldValue } = require('@google-cloud/firestore');

// Create a new client
const firestore = new Firestore();

async function quickstart() {
  // Obtain a document reference.
  const document = firestore.doc('posts/intro-to-firestore');

  // Enter new data into the document.
  const data = {
    title: 'Welcome to Firestore',
    body: 'Hello World',
    num: 1,
    date: FieldValue.serverTimestamp(),
  };
  await document.set(data);
  console.log('Entered new data into the document: ', data);

  // Update an existing document.
  const update = {
    body: 'My first Firestore app',
    num: FieldValue.increment(1),
  };
  await document.update(update);
  console.log('Updated an existing document: ', update);

  // Read the document.
  let doc = await document.get();
  console.log('Read the document, data: ', doc.data());

  // Delete the document.
  await document.delete();
  console.log('Deleted the document');
}
quickstart();
```
Note the output shows the sentinels basically being ignored:
```
jesss-mbp:repository $ node test.js 
Entered new data into the document:  {
  title: 'Welcome to Firestore',
  body: 'Hello World',
  num: 1,
  date: ServerTimestampTransform {}
}
Updated an existing document:  {
  body: 'My first Firestore app',
  num: NumericIncrementTransform { operand: 1 }
}
Read the document, data:  {
  num: 1,
  body: 'My first Firestore app',
  title: 'Welcome to Firestore'
}
Deleted the document
```
  2. Now revert the version of the library to 3.7.5 and try again... much better:
```
jesss-mbp:repository $ npm install @google-cloud/firestore@3.7.5

jesss-mbp:repository $ node test.js 
Entered new data into the document:  {
  title: 'Welcome to Firestore',
  body: 'Hello World',
  num: 1,
  date: ServerTimestampTransform {}
}
Updated an existing document:  {
  body: 'My first Firestore app',
  num: NumericIncrementTransform { operand: 1 }
}
Read the document, data:  {
  date: Timestamp { _seconds: 1589798022, _nanoseconds: 887000000 },
  num: 2,
  body: 'My first Firestore app',
  title: 'Welcome to Firestore'
}
Deleted the document
```

**Comment by schmidt-sebastian** [comment] 2020-05-21 17:51
@jessmorecroft Thanks for filing this! 
Note that issues like these are almost always due to version conflicts between two different instances of `@google-cloud/firestore`. While you only seem to be using a single version in your code, do you mind double-checking (via `npm list`). There is no obvious change in 3.8 that would have affected this behavior.

With your repro, I get:

```
Entered new data into the document:  {
  title: 'Welcome to Firestore',
  body: 'Hello World',
  num: 1,
  date: ServerTimestampTransform {}
}
Updated an existing document:  {
  body: 'My first Firestore app',
  num: NumericIncrementTransform { operand: 1 }
}
Read the document, data:  {
  body: 'My first Firestore app',
  num: 2,
  date: Timestamp { _seconds: 1590083287, _nanoseconds: 655000000 },
  title: 'Welcome to Firestore'
}
Deleted the document
```

package.json:
```
{
  "name": "quickstart",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/firestore": "^3.8.0"
  }
}
```

**Comment by jessmorecroft** [comment] 2020-05-21 22:12
Hi @schmidt-sebastian,

Just tried this and still no luck. 

```
jesss-mbp:repository jessmorecroft$ npm list | grep firestore
├─┬ @google-cloud/firestore@3.8.0
```

FYI, my package file at the bottom. Basically I'm trying to upgrade the library in my repo (https://gitlab.com/jmorecroft/repository) and my sentinel test is now failing.. could this be some weird incompatibility with the emulator introduced in the latest version perhaps?

Here's the gcloud version installed on the Docker image I'm using showing the emulator version:

```
/ # gcloud --version
Google Cloud SDK 270.0.0
beta 2019.05.17
bq 2.0.49
cloud-firestore-emulator 1.10.0
core 2019.11.04
gsutil 4.46
```

package.json:

```
{
  "name": "@jmorecroft67/repository",
  "version": "3.0.0",
  "description": "Generic repository interface and implementations for Firestore and in-memory.",
  "main": "dist/index.js",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "tsc -p tsconfig.build.json",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "node node_modules/.bin/jest --runInBand",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "postversion": "git push --follow-tags"
  },
  "files": [
    "/dist"
  ],
  "types": "dist/index.d.ts",
  "repository": {
    "type": "git",
    "url": "https://gitlab.com/jmorecroft/repository.git"
  },
  "keywords": [
    "repository",
    "firestore"
  ],
  "author": "Jess Morecroft",
  "license": "ISC",
  "bugs": {
    "url": "https://gitlab.com/jmorecroft/repository.git"
  },
  "homepage": "https://gitlab.com/jmorecroft/repository/-/blob/master/README.md",
  "dependencies": {
    "@google-cloud/firestore": "^3.8.0",
    "diff-arrays-of-objects": "^1.1.5",
    "fp-ts": "^2.5.2",
    "io-ts": "^2.1.2",
    "io-ts-types": "^0.5.6",
    "monocle-ts": "^2.1.0",
    "newtype-ts": "^0.3.4",
    "rxjs": "^6.5.4",
    "uuid": "^7.0.1"
  },
  "devDependencies": {
    "@types/jest": "^25.1.3",
    "@types/node": "^13.7.7",
    "@types/uuid": "^7.0.0",
    "@typescript-eslint/eslint-plugin": "^2.21.0",
    "@typescript-eslint/parser": "^2.21.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "jest": "^25.1.0",
    "prettier": "^1.19.1",
    "ts-jest": "^25.2.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.8.2"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

**Comment by schmidt-sebastian** [comment] 2020-05-22 01:09
I am not sure how to proceed further here. We have seen a lot of reports with strange behavior on Jest is used. Have you tried disabling Jest to see if this issue reproduces?

See also here: https://github.com/firebase/firebase-admin-node/issues/793

**Comment by jessmorecroft** [comment] 2020-05-22 01:39
Hi Sebastian,

I don’t think that’d matter as am not using Jest here, but will have a play.

Can you clarify how you are testing? Are you connecting to an emulator or Firestore proper? If the former what version of the emulator are you using?

Cheers 
Jess

**Comment by schmidt-sebastian** [comment] 2020-05-22 01:45
I cannot repro the issue against Firestore production or the emulator.

**Comment by jessmorecroft** [comment] 2020-05-22 04:04
Hi again @schmidt-sebastian ,

Well I think I figured it out. I just upgraded my emulator via `gcloud components upgrade` and it now works. So obviously there's an incompatibility with 3.8 and the older Firestore emulation. As I say, works fine with 3.7.5 so there must something in 3.8.0 that doesn't play nicely. Easy enough to fix for my local testing just by using the later gcloud.. unfortunately the docker image I'm using in my CI is configured/fixed to the earlier version of gcloud so I'll have to find another image.

To be clear, this emulator version is not working:
```
jesss-mbp:~ jessmorecroft$ gcloud --version
Google Cloud SDK 279.0.0
beta 2019.05.17
bq 2.0.53
cloud-datastore-emulator 2.1.0
cloud-firestore-emulator 1.10.2
core 2020.01.31
gsutil 4.47
kubectl 2019.11.04
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update
```

This updated version is working:
```
jesss-mbp:~ jessmorecroft$ gcloud --version
Google Cloud SDK 293.0.0
beta 2019.05.17
bq 2.0.57
cloud-datastore-emulator 2.1.0
cloud-firestore-emulator 1.11.3
core 2020.05.15
gsutil 4.50
kubectl 2020.05.01
```

Thanks for your help.

Cheers
Jess

**Comment by schmidt-sebastian** [comment] 2020-05-26 16:52
I checked with one of the contributors of the Emulator. They cannot explain the behavior you observed, but they also mentioned that there is likely nothing they can do since they only support the latest emulator version. Given that, I will close this issue. Please do let us know if this happens to block you again.

Thank you for your patience!

**Closed by schmidt-sebastian** 2020-05-26 16:52 UTC
Labels: :rotating_light:, api: firestore, triage me

**Comment by jessmorecroft** [comment] 2020-05-26 21:36
How bizarre!

No problem. I’ll just be sure to use a later version. 

Thanks for taking a look.
