### ISSUE TITLE
Bandwidth Exhausted while doing Firestore calls through NodeJS Server deployed on Google App Engine.

### ISSUE THREAD

**Issue by zulqarnainhanif** [googleapis/nodejs-firestore#765] opened 2019-09-25 13:41 UTC
- Node.js version: v10.16.0
  - npm version: 6.10.2
  - google-cloud-node version: Google Cloud SDK 262.0.0

The following are the dependencies used in my NodeJs project.
 
```
"dependencies": {
    "@google-cloud/firestore": "^2.2.4",
    "@google-cloud/storage": "^3.0.2",
    "@sendgrid/mail": "^6.4.0",
    "axios": "^0.19.0",
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "firebase-admin": "^8.2.0",
    "is-base64": "^0.1.0",
    "moment": "^2.24.0",
    "qs": "^6.8.0"
  },
```

While doing query request on firestore, sometime we get the error mentioned below and all the calls to firestore after that starts giving the same error. After another deployment with no changes all the apis works fine. I am still unable to figure out the leading cause of this error.

```
2019-09-25 12:33:27 default[20190924t162236]  { Error: Bandwidth exhausted
2019-09-25 12:33:27 default[20190924t162236]      at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
2019-09-25 12:33:27 default[20190924t162236]      at Http2CallStream.emit (events.js:203:15)
2019-09-25 12:33:27 default[20190924t162236]      at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
2019-09-25 12:33:27 default[20190924t162236]      at process._tickCallback (internal/process/next_tick.js:61:11)
2019-09-25 12:33:27 default[20190924t162236]    code: 8,
2019-09-25 12:33:27 default[20190924t162236]    details: 'Bandwidth exhausted',
2019-09-25 12:33:27 default[20190924t162236]    metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

Can someone please explain how to resolve this issue or handle this error so that it doesn't effect the other apis?

**Comment by schmidt-sebastian** [comment] 2019-09-30 17:22
@zulqarnainhanif Thanks for filing this issue and sorry to hear about your troubles. We have seen other reports internally and believe that the underlying issue is a RESOURCE_EXHAUSTED error from the backend. To debug your case, we will likely need project specific information, which will help us look at the workload at the time you experienced this error. 

Do you mind sharing your Project ID with us via a customer service request (via https://cloud.google.com/support/)? Thank you!

I will close this issue for now as this is likely project specific.

**Comment by schmidt-sebastian** [comment] 2019-10-01 14:53
I am re-opening this for now as @mikelehen tracked down an internal root cause for these error messages. The error seems to only reproduce with Node v10.16.3 and v12.11.0 and is likely caused by https://github.com/nodejs/node/issues/29223

You can work around this by downgrading the network layer for Firestore to an implementation that does not rely on Node's HTTP/2 network stack. This can be done as such:

```
const admin = require("firebase-admin");
const grpc = require("grpc");

admin.initializeApp();

const firestore = admin.firestore();
firestore.settings({grpc});
```

**Comment by schmidt-sebastian** [comment] 2019-10-02 21:09
@zulqarnainhanif We were able to confirm that https://github.com/nodejs/node/issues/29223 is indeed the root cause. We hope to get this fixed in the underlying Node implementation soon.

**Comment by schmidt-sebastian** [comment] 2020-01-02 22:08
The fix for the underlying issue in the HTTP2 layer will be part of Node 10.18.1 (https://github.com/nodejs/node/pull/30796), Node 12.3.2 (https://github.com/nodejs/node/pull/30865) and Node 12.4.1 (https://github.com/nodejs/node/pull/31069). We still have to wait for these builds to be released and become available on GCP, but since there is nothing to be done in this library, I am closing this issue for now. Thank you for your patience.

**Closed by schmidt-sebastian** 2020-01-02 22:08 UTC
Labels: external, priority: p2, type: bug

**Comment by arashkay** [comment] 2020-01-29 04:21
We are facing the same issue `Bandwidth exhausted` in our production environment we requests are high.

<img width="380" alt="Screen Shot 2020-01-29 at 3 18 00 pm" src="https://user-images.githubusercontent.com/1198006/73327604-c417f780-42aa-11ea-971c-9f600a533175.png">

I tried your support link @schmidt-sebastian but it seems there's no place to create a ticket unless we pay for it and upgrade to paid support plans?

Can you please let us know if this is something that will be fixed soon?

**Comment by schmidt-sebastian** [comment] 2020-01-29 20:41
@arashkay Unfortunately, you will have to wait until Node 10.18.1 is deployed to our container frameworks. Per https://cloud.google.com/functions/docs/concepts/exec, the version is currently at 10.15.3.

**Comment by ryansydnor** [comment] 2020-02-03 00:07
This is also happening to me in the Node 11.12 Docker image. `firestore.settings({grpc});` seems to have fixed the problem for now!

**Comment by schmidt-sebastian** [comment] 2020-02-03 17:05
@ryansydnor `firestore.settings({grpc})` bypasses this problem by using a different HTTP/2 stack. 

When you can switch to one of the Node version ranges mentioned above (Node 10.18.1+, Node 12.3.2+ and Node 12.4.1+), then you can switch back to the main GRPC stack. This should again reduce your binary size and startup time. 

Do note that Node's version ranges are distinct and that the bug is addressed individually in each version - i.e. the fix in 10.1.8.1 is not part of Node 11.x or Node 12.0.

**Comment by asifmadnan** [comment] 2020-04-21 20:46
If I use current stable version 12.16.2 will it be sufficient?

**Comment by schmidt-sebastian** [comment] 2020-04-21 21:02
It should be.

**Comment by dooleyb1** [comment] 2020-05-08 15:17
Experiencing a similar issue when performing some reasonably light stress testing on my API which interacts with Firestore using `"firebase-admin": "^8.12.0"` (NodeJS). 

Performing a stress test which replicates 600 users sending 4 requests each arriving at a rate of around 10 users p/s over 60s (2400 API requests in total each of which perform several reads and writes).

I am doing such a stress test as I have recently moved to [Distributed Counters](https://firebase.google.com/docs/firestore/solutions/counters#web) off the back of an issue I was having in relation to contention issues - see https://github.com/firebase/firebase-admin-node/issues/856#issuecomment-618793788.

Approx 2k of these requests succeed as expected and around 400 fail due to the following error:

```
{"code":8,"details":"Bandwidth exhausted","metadata":{"internalRepr":[],"options":{}}}
```

**Comment by dooleyb1** [comment] 2020-05-11 10:27
> pc});

This seems to have resolved the `Bandwidth exhausted issue`. Thanks!

**Comment by Limule** [comment] 2021-04-26 15:17
@dooleyb1 Hi, how did you solve it ?

**Comment by klon** [comment] 2021-05-04 17:18
We are seeing this issue randomly occurring in our App Engine Flex NodeJS instances running Node 14.16.1 and Firestore Admin SDK 9.2.0. Once it starts all further Firestore requests fail with `Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted` rendering the instance useless and forcing us to manually delete in in the App Engine console. Extremely unfortunate behavior that we need a speedy resolution to.

**Comment by navidshad** [comment] 2021-07-05 21:08
I had same problem for reading all data from firebase, after a while I figured out if we stop this process and run a new process we can pass the error and continue the job.

then I used child-process and it helped me:
- I did write a parent script and a child script,
- Parent script runs child script as a child-process,
- The child goes through a collection until get [8 RESOURCE_EXHAUSTED] error, then send a message to parent to inform it from the error.
- Then parent kills child and create a new one and tells it where to start reading again.

This is a solution works 100 percent, but it's a little advance and beginners-intermediates may could not able to implement it.

**Comment by kirillgroshkov** [comment] 2021-07-06 10:37
> * Then parent kills child and create a new one and tells it where to start reading again.

@navidshad how do you pass the "where to start reading again" part? Do you use some kind of cursor?

I tried the same approach with child-process some years ago, it almost worked, but I think I got stuck with cursors (it was `datastore`, not `firestore`, at that moment, if it matters).

**Comment by navidshad** [comment] 2021-07-06 15:04
> > * Then parent kills child and create a new one and tells it where to start reading again.
> 
> @navidshad how do you pass the "where to start reading again" part? Do you use some kind of cursor?
> 
> I tried the same approach with child-process some years ago, it almost worked, but I think I got stuck with cursors (it was `datastore`, not `firestore`, at that moment, if it matters).

Actually I have write a cursor that manage everything relative with that issue. I can put the code here
