### ISSUE TITLE
ERROR: Could not resolve "assert", "stream", "url" when deploy app to Vercel

### ISSUE THREAD

**Issue by juniorforlife** [googleapis/nodejs-firestore#2089] opened 2024-07-25 08:42 UTC
#### Environment details

  - OS: whatever OS Vercel is using
  - Node.js version: 18x
  - npm version: Bun 1.0
  - `@google-cloud/firestore` version: ^7.9.0

#### Steps to reproduce

  1. Install and use @google-cloud/firestore like normal
  2. Deploy your app to Vercel
  3. Deployment will fail with this error. Note I'm not using edge functions 
  ```
error during build:
Error: Build failed with 78 errors:
node_modules/@google-cloud/firestore/build/src/aggregate.js:20:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/bulk-writer.js:4:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/document.js:20:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/index.js:19:25: ERROR: Could not resolve "stream"
node_modules/@google-cloud/firestore/build/src/index.js:20:22: ERROR: Could not resolve "url"
```

**Comment by cherylEnkidu** [comment] 2024-07-25 13:13
Hi @juniorforlife ,

The issue is not likely related to Firestore SDK, you might need to talk to Vercel team to ask for help. Here is the link I found might related to your question (https://stackoverflow.com/questions/74965694/vercel-build-deply-error-npm-err-eresolve-unable-to-resolve-dependency-tree). I will close this ticket for now but feel free to reopen it.

**Closed by cherylEnkidu** 2024-07-25 13:13 UTC
Labels: priority: p2, type: bug, api: firestore
