### ISSUE TITLE
Typescript error when updating data with index signatures with an object as the value

### ISSUE THREAD

**Issue by mrjoshua520** [googleapis/nodejs-firestore#1808] opened 2022-12-28 23:12 UTC
#### Environment details

  - OS: Windows 10
  - Node.js version: 18.12.1
  - npm version: 9.2.0
  - `@google-cloud/firestore` version: 6.4.1

#### Steps to reproduce
Here is the code giving the error
```ts
import { DocumentReference } from "@google-cloud/firestore";

type DocumentDataType = {
    [key: string]: {value: boolean};
}

function main(documentRef: DocumentReference<DocumentDataType>, data: DocumentDataType) {
    documentRef.update(data);
}
```
I've created this repository https://github.com/mrjoshua520/MinToReproduce-TransactionUpdateFieldValue/blob/main/index.ts 

1. Clone Repository
2. Run `npm ci`
3. Run `npm run build`

Here is the error that was obtained after following those steps
```
index.ts:8:24 - error TS2345: Argument of type 'DocumentDataType' is not assignable to parameter of type '{ [x: string]: FieldValue | { value?: boolean | FieldValue | undefined; } | undefined; } & AddPrefixToKeys<string, { value?: boolean | FieldValue | undefined; }>'.
  Type 'DocumentDataType' is not assignable to type 'AddPrefixToKeys<string, { value?: boolean | FieldValue | undefined; }>'.
    'string' and '`${string}.value`' index signatures are incompatible.
      Type '{ value: boolean; }' is not assignable to type 'boolean | FieldValue | undefined'.

8     documentRef.update(data);
                         ~~~~


Found 1 error in index.ts:8
```

**Comment by nstringham** [comment] 2022-12-29 00:30
We are using this workaround:
```ts
documentRef.update(data satisfies DocumentDataType as any);
```

**Comment by cherylEnkidu** [comment] 2022-12-29 02:28
Hi,

Thank you for filling up the ticket! The team is not available for support during the holiday break and we will get back to you in the new year. Happy holiday!

**Comment by cherylEnkidu** [comment] 2023-01-03 00:56
Duplicate of https://github.com/googleapis/nodejs-firestore/issues/1745

Hi,

Thanks for filling the ticket! Our team is aware of this issue and is working on the solution.

**Closed** 2023-01-03 00:56 UTC
Labels: priority: p2, type: bug, api: firestore
