### ISSUE TITLE
Show stacktrack from source file in error messages

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#756] opened 2019-09-14 19:36 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look at my server logs and see a firestore error but have no idea where in my code the error is occurring.

For instance, I will get errors like this:
```
Error: Too much contention on these documents. Please try again.
    at Http2CallStream.<anonymous> (/api/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:214:15)
    at /api/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
It is very difficult to determine where in my code this happens without having try catch blocks around every single firestore call.

 **Describe the solution you'd like**
The error should include the source files in the call stack. For instance, if that error occurs on line 52 of myfile.js, the stacktrace should that in the trace.

**Comment by schmidt-sebastian** [comment] 2019-09-16 16:08
@jakeleventhal Thanks for filing this! You are not alone here - I do think there is some room for improvement here. I will discuss this internally, but we should be able to get this fixed in the next release or two.

**Comment by thebrianchen** [comment] 2019-10-01 22:11
I've dug into this issue, and it seems like the root cause is that stack traces are not preserved across async callbacks. As a result, such a change would require capturing and passing the stack trace across all async calls, which would involve a substantial rework of the client. Unfortunately, this is not in our immediate scope, but we are open to revisiting this later. If you know of any other workarounds, please let us know! However, enabling logging in Firestore would hopefully provide enough information for you to debug your case.

**Closed by thebrianchen** 2019-10-01 22:11 UTC
Labels: priority: p1
