### ISSUE TITLE
Unhandled error event for document get() on Error: 14 UNAVAILABLE: Name resolution failed for target firestore.googleapis.com:443

### ISSUE THREAD

**Issue by yonbh** [googleapis/nodejs-firestore#1270] opened 2020-07-21 14:26 UTC
#### Environment details

  - OS: macOS Catalina 10.15.4
  - Node.js version: 14.4
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.7.1

#### Steps to reproduce
Problematic method: DocumentSnapshot `get()`

This error happens occasionally (I am assuming due to instance network outage or dns errors) but it is unable to be handled properly as the error does not seem to be propagated back up due to it being unhandled from the firestore package as intended for document `get()` method. For comparison, the `set()` method handles it properly so the error can be caught in our api.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Name resolution failed for target firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)
    at ChannelImplementation.tryPick (/api/node_modules/@grpc/grpc-js/build/src/channel.js:214:32)
    at ChannelImplementation._startCallStream (/api/node_modules/@grpc/grpc-js/build/src/channel.js:244:14)
    at Http2CallStream.start (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:418:22)
Emitted 'error' event on ClientReadableStreamImpl instance at:
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:327:28)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    [... lines matching original stack trace ...]
    at Http2CallStream.start (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:418:22)
    at BaseStreamingInterceptingCall.start (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:275:19) {
  code: 14,
  details: 'Name resolution failed for target firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

To easily reproduce the error, network access was disabled on the machine to cause the dns error.
Then tested it with a simple api:

```

const { Firestore } = require('@google-cloud/firestore');
const client = new Firestore();

function get() {
  const doc = client.doc('test_user/user.person1');

  doc.get().then((res) => {
    console.log('get_result', res);
  }).catch((err) => {
    console.error('get_error', err);
  });
}

function set() {
  const doc = client.doc('test_user/user.person2');

  doc.set({ name: 'humanName' }).then((res) => {
    console.log('set_result', res);
  }).catch((err) => {
    console.error('set_error', err);
  });
}

set(); // error caught properly
get(); // error not caught properly
```

which would produce this:

```
set_error Error: 14 UNAVAILABLE: Name resolution failed for target firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)
    at ChannelImplementation.tryPick (/api/node_modules/@grpc/grpc-js/build/src/channel.js:214:32)
    at Object.updateState (/api/node_modules/@grpc/grpc-js/build/src/channel.js:82:26) {
  code: 14,
  details: 'Name resolution failed for target firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Name resolution failed for target firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)
    at ChannelImplementation.tryPick (/api/node_modules/@grpc/grpc-js/build/src/channel.js:214:32)
    at ChannelImplementation._startCallStream (/api/node_modules/@grpc/grpc-js/build/src/channel.js:244:14)
    at Http2CallStream.start (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:418:22)
Emitted 'error' event on ClientReadableStreamImpl instance at:
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:327:28)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    [... lines matching original stack trace ...]
    at Http2CallStream.start (/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:418:22)
    at BaseStreamingInterceptingCall.start (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:275:19) {
  code: 14,
  details: 'Name resolution failed for target firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

I think it would be better if this error produced from `get()` can be handled similarly to `set()`.

**Comment by yonbh** [comment] 2020-07-22 10:53
I suspect the problem lies in following functions and their interactions in the package located in index.js file:

- getAll()
- getAll_()
- requestStream()

In which getAll_() is unable to receive the error that has happened in requestStream().

**Comment by yonbh** [comment] 2020-07-23 09:37
An odd behaviour can also be observed where in some rare occasions, the error from `get()` was properly handled. This can be easily replicated with a simple interval like this:

```
process.on('uncaughtException', function (err, res) {
  console.error('uncaught_err', err.message);
  console.error('uncaught_res', res);
});

setInterval(function () {
  get();
}, 8000);

get();
set();

```

**Comment by schmidt-sebastian** [comment] 2020-07-28 16:56
@yonbh Thanks for filing this and sorry for not getting back to you earlier.

We made no noteworthy changes in these codepaths since the 4.x release. Changes in networking behavior probably point at updates in our networking stack. Do you happen to know what versions of `@grpc/grpc-js` you were using in your experiments?

That being said, we cam already rety requests for `getAll()` that fail with UNAVAILABLE. This retry, however, currently doesn't kick in if we have received results from the server (that doesn't seem to be the case here). We can probably be smarter and retry `getAll` regardless. Do you happen to have output from `setLogFunction` for one of your problematic runs?

**Comment by yonbh** [comment] 2020-07-28 18:21
> @yonbh Thanks for filing this and sorry for not getting back to you earlier.
> 
> We made no noteworthy changes in these codepaths since the 4.x release. Changes in networking behavior probably point at updates in our networking stack. Do you happen to know what versions of `@grpc/grpc-js` you were using in your experiments?
> 
> That being said, we cam already rety requests for `getAll()` that fail with UNAVAILABLE. This retry, however, currently doesn't kick in if we have received results from the server (that doesn't seem to be the case here). We can probably be smarter and retry `getAll` regardless. Do you happen to have output from `setLogFunction` for one of your problematic runs?

Thanks for looking into this!

The `@grpc/grpc-js` version I had was `1.0.5`.

I don't think I have any output from `setLogFunction`. May I know how to access that?
I ran the experiment to replicate the error just on a local machine and using the package via gcp credential file.

**Comment by schmidt-sebastian** [comment] 2020-07-28 23:49
I think they first step should be to update to the latest version of https://www.npmjs.com/package/@grpc/grpc-js. Otherwise, our trusted colleagues will likely not spend a lot of time debugging this :)

`setLogFunction` is a top-level function in our API. See here: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L45

**Comment by yonbh** [comment] 2020-07-29 10:46
I am still observing the same behaviour after:

- Minor package version upgrade to 3.8.6 (I have also previously update to 4.1.1 but that did not help as well)
- Using npm-force-resolutions to update the`@grpc/grpc-js` version to `1.1.3` which was listed as dependency for `@google-cloud/firestore` (was previously listed to use `1.0.5` in the package).

I have tried utilising setLogFunction and this is an example output after replicating the error from using document snapshot `get()`.

```
Firestore (3.8.6) 2020-07-29T10:30:04.518Z BLNKq [ClientPool.acquire]: Creating a new client
Firestore (3.8.6) 2020-07-29T10:30:04.591Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (3.8.6) 2020-07-29T10:30:04.595Z ##### [Firestore.initializeIfNeeded]: Detected project ID: project-id
Firestore (3.8.6) 2020-07-29T10:30:04.596Z BLNKq [ClientPool.acquire]: Re-using existing client with 100 remaining operations
Firestore (3.8.6) 2020-07-29T10:30:04.596Z BLNKq [Firestore.requestStream]: Sending request: {"database":"projects/project-id/databases/(default)","documents":["projects/project-id/databases/(default)/documents/test_user/user.person1"]}
Firestore (3.8.6) 2020-07-29T10:30:10.970Z BLNKq [Firestore._initializeStream]: Received initial error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:156:22)
    at Http2CallStream.endCall (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:142:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:467:14)
    at ChannelImplementation.tryPick (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:238:32)
    at Object.updateState (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:107:26)
    at ResolvingLoadBalancer.updateState (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js:173:35) {
  code: 14,
  details: 'Name resolution failed for target dns:firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Firestore (3.8.6) 2020-07-29T10:30:10.970Z BLNKq [Firestore._initializeStream]: Received stream end
Firestore (3.8.6) 2020-07-29T10:30:10.971Z BLNKq [Firestore._initializeStream]: Received stream end
Firestore (3.8.6) 2020-07-29T10:30:10.971Z BLNKq [Firestore._retry]: Retrying request that failed with error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:156:22)
    at Http2CallStream.endCall (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:142:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:467:14)
    at ChannelImplementation.tryPick (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:238:32)
    at Object.updateState (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:107:26)
    at ResolvingLoadBalancer.updateState (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js:173:35) {
  code: 14,
  details: 'Name resolution failed for target dns:firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Firestore (3.8.6) 2020-07-29T10:30:10.972Z ##### [ExponentialBackoff.backoffAndWait]: Backing off for 807.097668254565 ms (base delay: 1000 ms)
Firestore (3.8.6) 2020-07-29T10:30:11.783Z BLNKq [ClientPool.acquire]: Re-using existing client with 100 remaining operations
Firestore (3.8.6) 2020-07-29T10:30:11.784Z BLNKq [Firestore.requestStream]: Sending request: {"database":"projects/project-id/databases/(default)","documents":["projects/project-id/databases/(default)/documents/test_user/user.person1"]}
Firestore (3.8.6) 2020-07-29T10:30:11.785Z BLNKq [Firestore._initializeStream]: Received initial error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:156:22)
    at Http2CallStream.endCall (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:142:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:467:14)
    at ChannelImplementation.tryPick (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:238:32)
    at ChannelImplementation._startCallStream (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:268:14)
    at Http2CallStream.start (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:445:22) {
  code: 14,
  details: 'Name resolution failed for target dns:firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Firestore (3.8.6) 2020-07-29T10:30:11.786Z BLNKq [Firestore._retry]: Retrying request that failed with error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:firestore.googleapis.com:443
    at Object.callErrorFromStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:156:22)
    at Http2CallStream.endCall (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:142:18)
    at Http2CallStream.cancelWithStatus (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:467:14)
    at ChannelImplementation.tryPick (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:238:32)
    at ChannelImplementation._startCallStream (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:268:14)
    at Http2CallStream.start (/api/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:445:22) {
  code: 14,
  details: 'Name resolution failed for target dns:firestore.googleapis.com:443',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Firestore (3.8.6) 2020-07-29T10:30:11.786Z ##### [ExponentialBackoff.backoffAndWait]: Backing off for 1313.9544295799767 ms (base delay: 1500 ms)
Firestore (3.8.6) 2020-07-29T10:30:13.104Z BLNKq [ClientPool.acquire]: Re-using existing client with 100 remaining operations
Firestore (3.8.6) 2020-07-29T10:30:13.104Z BLNKq [Firestore.requestStream]: Sending request: {"database":"projects/project-id/databases/(default)","documents":["projects/project-id/databases/(default)/documents/test_user/user.person1"]}

uncaught_err 14 UNAVAILABLE: Name resolution failed for target dns:firestore.googleapis.com:443
uncaught_res uncaughtException
```

With the similiar setup as before for example:
```
process.on('uncaughtException', function (err, res) {
  console.error('uncaught_err', err.message);
  console.error('uncaught_res', res);
});

const firestore = require('@google-cloud/firestore');
const client = new firestore.Firestore();

firestore.setLogFunction(console.error);

function get() {
  const doc = client.doc('test_user/user.person1');

  doc.get().then((res) => {
    console.log('get_result', res);
  }).catch((err) => {
    console.error('get_error', err);
  });
}

get();
```

**Comment by schmidt-sebastian** [comment] 2020-08-07 05:48
@yonbh Sorry for being so slow here :/ I am not able to reproduce this. For me, the catch handler is invoked (after a lot of backoff) and the uncaughtException is not called. I was however not able to generate the same error that you were seeing, but tried with various other errors (such as specifying an invalid host). I'll ponder more about this, but for now I don't see an obvious problem in our code that we could fix.

**Comment by laljikanjareeya** [comment] 2020-09-11 07:00
@yonbh I am able to reproduce the issue in `3.7.1` `get()` does not handle the error properly.

I have run demo that you have given above with Version `4.0.0` or above it works fine, It handle the error properly.

Closing this issue feel free to reopen the issue.

**Closed by laljikanjareeya** 2020-09-11 07:00 UTC
Labels: :rotating_light:, api: firestore, triage me

**Comment by yonbh** [comment] 2020-09-22 14:36
@laljikanjareeya Sorry for the late reply. I have tested it with version `4.2.0` and it looks to be working properly now. Many thanks 😊!
