### ISSUE TITLE
Custom Converter does not work when using update method

### ISSUE THREAD

**Issue by inaridiy** [googleapis/nodejs-firestore#1786] opened 2022-10-14 10:01 UTC
#### Environment details

  - OS: Windows 10 Pro 21H2
  - Node.js version: v16.17.0
  - npm version: 8.15.0
  - `@google-cloud/firestore` version:6.3.0

#### Steps to reproduce

  1.  execute DocumentReference.update method with custom converter set.

### Demonstration
```ts
// user is instanceOf User Class
await db
      .collection("user")
      .doc(user.address.value)
      .withConverter(UserConverter({ includeCreatedAt: false }))
      .update(user);
// Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "dataOrField" is not a valid Firestore document. Couldn't serialize object of type "User". Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```
Since User is incompatible with FieldValue, it must be converted using UserConverter, but it seems that the update method does not use Converter and evaluates it directly.

I have used create and set methods in other places, but have not seen the same problem.

### Survey
Within the WriteBatch Class The ref._converter was called inside the create and set methods, but not inside the update method.

>Where Converter is called
https://github.com/googleapis/nodejs-firestore/blob/80cfca91144eb963e2b28a037ce5d45b0bd2fa6e/dev/src/write-batch.ts#L197-L199
https://github.com/googleapis/nodejs-firestore/blob/80cfca91144eb963e2b28a037ce5d45b0bd2fa6e/dev/src/write-batch.ts#L332-L340

>Converter is not called within Update
https://github.com/googleapis/nodejs-firestore/blob/80cfca91144eb963e2b28a037ce5d45b0bd2fa6e/dev/src/write-batch.ts#L425-L434

**Comment by MarkDuckworth** [comment] 2022-10-17 21:06
Thanks for bringing this to our attention. I'll have to look at this a little more, but my first thought is that update is expecting a different type of object `UpdateData<T>`, which is an object with all of the properties of T and allows you to set properties using dot notation. So, this might be expected.

**Comment by MarkDuckworth** [comment] 2022-10-25 20:28
Relates to https://github.com/googleapis/nodejs-firestore/issues/1745. You might be interested in reviewing that thread for a different perspective on this. We're also looking at this internally.

**Comment by dconeybe** [comment] 2022-11-10 20:40
Closing as a duplicate of https://github.com/googleapis/nodejs-firestore/issues/1745.

**Closed by dconeybe** 2022-11-10 20:40 UTC
Labels: priority: p2, type: bug, api: firestore
