### ISSUE TITLE
isEqual type error when updating a nested object with converter

### ISSUE THREAD

**Issue by VictorLeach96** [googleapis/nodejs-firestore#1793] opened 2022-10-31 22:13 UTC
#### Environment details

  - `@google-cloud/firestore` version: ^6.4.1

#### Steps to reproduce

Adding a nested object works correctly, however updating it will cause a type error.

```typescript
import * as firestore from '@google-cloud/firestore'

const db = new firestore.Firestore()

interface Model {
  object: Record<string, { nested: boolean }>
}

const converter: firestore.FirestoreDataConverter<Model> = {
  fromFirestore: (snap: firestore.QueryDocumentSnapshot) => snap.data() as Model,
  toFirestore: (data: Model) => data
}

const main = async () => {
  const object: Record<string, { nested: boolean }> = {
    key: {
      nested: true
    }
  }

  const ref = await db.collection('').withConverter(converter).add({
    object
  })

  await ref.update({
    object
  })
}
main()
```

The following type error occurs on the update method.

```
Type 'Record<string, { nested: boolean; }>' is not assignable to type 'FieldValue | ({ [x: string]: FieldValue | { nested?: boolean | FieldValue | undefined; } | undefined; } & AddPrefixToKeys<string, { nested?: boolean | FieldValue | undefined; }>) | undefined'.
  Property 'isEqual' is missing in type 'Record<string, { nested: boolean; }>' but required in type 'FieldValue'.ts(2322)

firestore.d.ts(2230, 5): 'isEqual' is declared here.

test.ts(6, 3): The expected type comes from property 'object' which is declared here on type '{ object?: FieldValue | ({ [x: string]: FieldValue | { nested?: boolean | FieldValue | undefined; } | undefined; } & AddPrefixToKeys<string, { nested?: boolean | FieldValue | undefined; }>) | undefined; } & AddPrefixToKeys<...>'
```

The `UpdateData` type seems to be having trouble working correctly with objects and `FieldValue`.

**Comment by cherylEnkidu** [comment] 2022-10-31 23:35
Duplicate of #1745 

Hi @VictorLeach96,

Thanks for filling the ticket! Our team is aware of this issue and is working on the solution.

**Closed by cherylEnkidu** 2022-10-31 23:35 UTC
Labels: priority: p2, type: bug, api: firestore
